config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'pages/about', :as => "about"

  get 'pages/services', :as => "services"

  get 'pages/contact', :as => "contact"

  get 'pages/faq', :as => "faq"

  get 'pages/quote', :as => "get-a-quote"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end

  def faq
  end

  def quote
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<p class="text-muted text-center">Tax Prep Montreal - 2016</p>
</div>

app/views/layouts/_google-analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73366835-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73366835-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TaxPrepMontreal.com</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Get a Quote", root_path, class: "btn btn-sucess" %></li>
        <li><%= link_to "Services", services_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tax Prep Montreal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/google_analytics' %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

<footer class="footer">
      <%= render 'layouts/footer' %>
</footer>

</body>
</html>

app/views/pages/_features.html.erb
<div class="row">
    <div class="col-sm-4">
        <img class="img-circle img-responsive img-center" src="http://i.imgur.com/GbUFLkB.png" alt="" style="width: 100px; margin-left: auto; margin-right: auto;">
        <h2>Hassle-Free</h2>
        <p>Let us take care of the boring parts of your life. We're really, really good at what we do.</p>
    </div>
    <div class="col-sm-4">
        <img class="img-circle img-responsive img-center" src="http://i.imgur.com/wENsyGp.png" alt="" style="width: 100px; margin-left: auto; margin-right: auto;">
        <h2>Lightning Fast</h2>
        <p>Your tax return will be ready to go within 14 days, allowing you the peace of mind to plan ahead.</p>
    </div>
    <div class="col-sm-4">
        <img class="img-circle img-responsive img-center" src="http://i.imgur.com/XZGkbBG.png" alt="" style="width: 100px; margin-left: auto; margin-right: auto;">
        <h2>Simple &amp; Dependable</h2>
        <p>Stop jumping through countless accountant hoops just to file your taxes. We keep it stupid simple.</p>
    </div>
</div>

app/views/pages/_importantdates.html.erb
<ul class="timeline">
    <li>
     <div class="timeline-badge info"><i class="glyphicon glyphicon-check"></i>
     </div>
     <div class="timeline-panel">
        <div class="timeline-heading">          
            <h4 class="timeline-title" name="rrsp-contributions">February 29th, 2016</h4>
                    <p><small class="text-muted">Deadline for RRSP Contributions</small>
                    </p>
        </div>
        <div class="timeline-body">
            <p>
                <a href="#">RRSP contributions</a> allow you to reduce your taxable income for the year by contributing to your Registered Retirement Savings Plan (RRSP).
            </p> 
            <br>
            <p>
                The maximum contribution for the year is indicated in your 2014 <a href="#">Notice of Assessment</a>.
            </p>
            </div>
        </div>
    </li>

    <li class="timeline-inverted">
        <div class="timeline-badge info">
            <i class="glyphicon glyphicon-credit-card"></i>
        </div>
        <div class="timeline-panel">
            <div class="timeline-heading">
                <h4 class="timeline-title" name="individuals-tax-returns">April 30th, 2016</h4>
                <p>
                    <small class="text-muted">Deadline to file Tax Returns for <strong>individuals</strong></small>
                </p>
            </div>
            <div class="timeline-body">
                <p>At the end of each year, every Canadian citizen and resident that has worked in Canada is required by the federal and provicial government to submit information outlining the revenues earned throughout the year. </p>
                <br>
                <p>This allows the government to calculate the amount of tax you'll be required to pay by April 30th, 2016.</p>
                <br>
                <p>Note: The date to make your payment to the governments is <strong>also</strong> April 30th, 2016, so plan ahead to get your tax return prepared earlier.</p>
                <p class="pull-right">
                    <a class="typeform-share btn btn-primary btn-small" href="https://eutait.typeform.com/to/OOIX17" data-mode="1" target="_blank">Get a quote >></a>
                </p>
            </div>
        </div>
    </li>

    <li>
        <div class="timeline-badge info">
            <i class="glyphicon glyphicon-credit-card"></i>
        </div>
        <div class="timeline-panel">
            <div class="timeline-heading">
                <h4 class="timeline-title" name="self-employed-tax-returns">June 15, 2016</h4>
                <p>
                    <small class="text-muted">Deadline to file Tax Returns for <strong>self-employed individuals</strong></small>
                </p>
            </div>
            <div class="timeline-body">
                <p>At the end of each year, every individual that has carried on a business in Canada is required by the federal and provicial government to submit information outlining the revenues earned throughout the year from that business.</p>
                <br>
                <p> This allows the government to calculate the amount of tax you'll be required to pay by April 30th, 2016.</p>
                <br>
                <p>Note: The date to make your payment to the governments is <strong>STILL</strong> April 30th, 2016, so plan ahead to get your tax return prepared earlier.</p>
                <p class="pull-right">
                    <a class="typeform-share btn btn-primary btn-small" href="https://eutait.typeform.com/to/OOIX17" data-mode="1" target="_blank">Get a quote >></a>
                </p>
            </div>
        </div>
    </li>

    <!-- <li class="timeline-inverted">
        <div class="timeline-panel">
            <div class="timeline-heading">
                <h4 class="timeline-title">Date 4</h4>
             </div>
             <div class="timeline-body">
                <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.
                </p>
             </div>
        </div>
    </li> -->

    <!-- <li>
        <div class="timeline-badge info"><i class="glyphicon glyphicon-floppy-disk"></i>
        </div>
        <div class="timeline-panel">
            <div class="timeline-heading">  
                <h4 class="timeline-title">Date 5</h4>
            </div>
            <div class="timeline-body">
                <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
                <hr>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-cog"></i>  <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </li> -->
        <!-- <li>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    
<h4 class="timeline-title">Date 6</h4>

                </div>
                <div class="timeline-body">
                    <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
                </div>
            </div>
        </li>
        <li class="timeline-inverted">
            <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i>
            </div>
            <div class="timeline-panel">
                <div class="timeline-heading">
                    
<h4 class="timeline-title">Date 7</h4>

                </div>
                <div class="timeline-body">
                    <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
                </div>
            </div>
        </li> -->
    </ul>

app/views/pages/_pricing.html.erb
<section class="section">
    			<div class="section-headlines text-center">
					<h2>Pricing Tiers</h2>
					<p>Montreal Tax Prep offers an efficient and quick tax return service for busy people. Pricing is determined based on your particular situation. We've outlined three pricing tiers for your convenience.</p>
				</div>

				<div class="row-fluid">
					<div class="pricing-table row-fluid text-center">
						<div class="span4">
							<div class="plan">
								<div class="plan-name">
									<h2>Basic</h2>
									<p class="muted">Perfect for small budget</p>
								</div>
								<div class="plan-price">
									<b>$19</b> / month
								</div>
								<div class="plan-details">
									<div>
										<b>Unlimited</b> Download
									</div>
									<div>
										<b>Free</b> Priority Shipping
									</div>
									<div>
										<b>Unlimited</b> Warranty
									</div>
								</div>
								<div class="plan-action">
									<a href="#" class="btn btn-block btn-large">Choose Plan</a>
								</div>
							</div>
						</div>

						<div class="span4">
							<div class="plan prefered">
								<div class="plan-name">
									<h2>Standard</h2>
									<p class="muted">Perfect for medium budget</p>
								</div>
								<div class="plan-price">
									<b>$39</b> / month
								</div>
								<div class="plan-details">
									<div>
										<b>Unlimited</b> Download
									</div>
									<div>
										<b>Free</b> Priority Shipping
									</div>
									<div>
										<b>Unlimited</b> Warranty
									</div>
								</div>
								<div class="plan-action">
									<a href="#" class="btn btn-success btn-block btn-large">Choose Plan</a>
								</div>
							</div>
						</div>

						<div class="span4">
							<div class="plan">
								<div class="plan-name">
									<h2>Advance</h2>
									<p class="muted">Perfect for large budget</p>
								</div>
								<div class="plan-price">
									<b>$59</b> / month
								</div>
								<div class="plan-details">
									<div>
										<b>Unlimited</b> Download
									</div>
									<div>
										<b>Free</b> Priority Shipping
									</div>
									<div>
										<b>Unlimited</b> Warranty
									</div>
								</div>
								<div class="plan-action">
									<a href="#" class="btn btn-block btn-large">Choose Plan</a>
								</div>
							</div>
						</div>
					</div>
					<p class="muted text-center">Note: You can change or cancel your plan at anytime in your account settings.</p>
				</div>
			</section>

app/views/pages/_quote.html.erb
<div class="row">
	<div class="bs-component">
		<div class="jumbotron">
			<h2 class="text-center">Tired of Running After Your Accountant?</h2>
			<h2 class="lead text-center">Get your income tax return in 14 days or less.</h2>

			<br>

			<p class="text-center">
				<a class="typeform-share btn btn-primary btn-lg" href="https://eutait.typeform.com/to/OOIX17" data-mode="1" target="_blank" style=" width: 300px;">Get a quote >></a>
			</p>

			<p class="text-center text-muted">Pricing is determined based on your particular situation. To get your pricing for the <a href="#">2015 Tax Return</a>, please take a few moments to fill out our short questionnaire by clicking above.</p>

			<%= render 'pages/typeform' %>

		</div>
	</div>
</div>

app/views/pages/_typeform.html.erb
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}id=id+'_';if(!gi.call(d,id)){qs=ce.call(d,'link');qs.rel='stylesheet';qs.id=id;qs.href=b+'share-button.css';s=gt.call(d,'head')[0];s.appendChild(qs,s)}})()</script>

app/views/pages/about.html.erb
<title>About | Tax Prep Montreal</title>

<div class="row">
	<div class="bs-component">
		<div class="jumbotron">
			<h3>About Tax Prep Montreal</h3>
				<p>Tax Prep Montreal is a Montreal accounting firm that has worked with individuals and small businesses from many economic, professional, and social backgrounds. We believe strongly in providing a simple, efficient portal for the average Joe looking to get their taxes sorted out without headaches.<p>

				<!-- <p>Our service is offered primarily by Alicia Barchechat, who holds a Bachelor of Commerce degree from Concordia University with a specialization in Accounting. She is currently awaiting the reception of her CPA, CGA permit. Her wide range of financial expertise and knowledge is evidenced by her education and strong employment background.</p>
 -->
				<p>Clients that choose to work with Tax Prep Montreal can be sure that they will be given the highest quality service and commitment. </p>

				<p>Our Tax Accounting clients include:
					<ul>
						<li>Entrepreneurs</li>
						<li>Consultants</li>
						<li>Young professionals</li>
						<li>Medium to high income families</li>
						<li>Employees</li>
					</ul>
				</p>

				<p>Need to get your personal income tax return filed? <a href="/">Learn more here.</a></p>
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<title>Contact | Tax Prep Montreal</title>

<div class="container">
    <div class="row">
    	<div class="col-md-3"></div>
        <div class="col-md-6">
            <div>
                <div class="well panel panel-default">
                    <div class="text-center header">Contact Information</div>
                    <div class="panel-body text-center">
                        <h4>Address</h4>
                        <div>
                        7486 Guelph<br />
                        Montreal, Quebec<br />
                        H4W 1H1, Canada<br />
                        alicia@taxprepmontreal.com<br />
                        </div>
                        <hr />
                        <a class="btn btn-primary" href="mailto:alicia@taxprepmontreal.com?Subject=Personal%20Tax%20Prep" target="_top">Email us</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

app/views/pages/faq.html.erb
<title>FAQ | Tax Prep Montreal</title>

<div class="jumbotron">
  <div class="container">
		<div class="page-header ">
  			<h1 class="text-center">Tax Return Preparation FAQ <br>
  				<small>You have questions, we have answers.</small></h1>
          <div class="text-center">
            Click on a question below to expand the answer.
          </div>
  	</div>
        <br><br> 
        <div class="panel-group" id="accordion">

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                  What is the deadline to submit my 2015 Tax Return?
                </a>
              </h4>
            </div>
            <div id="collapseFour" class="panel-collapse collapse ">
              <div class="panel-body">
                The deadline to submit your tax return as well as other important dates can be found at the bottom of our <a href="/">home page.</a</div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
                  What is the deadline to make my RRSP contributions for 2015?
                </a>
              </h4>
            </div>
            <div id="collapseSix" class="panel-collapse collapse">
              <div class="panel-body">
         The deadline to make your RRSP contributions as well as other important dates can be found at the bottom of our <a href="/">home page.</a
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
        How do I pay for your Tax Prep service?</a>
              </h4>
            </div>
            <div id="collapseFive" class="panel-collapse collapse">
              <div class="panel-body">
              Once your tax return is complete and ready-to-go, you'll be sent a secure online payment link to claim it. Payment options include all major credit cards.  
              </div>
            </div>
          </div>
                
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
                  What do I do if I'm missing forms?
                </a>
              </h4>
            </div>
            <div id="collapseSeven" class="panel-collapse collapse">
              <div class="panel-body">
                  In the likely event that you've misplaced or lost a form that we need, we can always retrieve the information from the Federal and Provincial governments, provided you've authorized us to contact them on your behalf by <a href="http://taxprepmontreal.x10host.com/Tax%20Prep%20Montreal%20-%20Personal%20Information%20Consent%20Forms.zip">filling out and signing these two documents.</a></div>
            </div>
          </div>
                
          <!-- <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseHeight">
                  Under what licence is OMA distributed </a>      </h4>
            </div>
            <div id="collapseHeight" class="panel-collapse collapse">
              <div class="panel-body">
                The OMA Browser is available under the Creative Commons Attribution-Share Alike 2.5 License, and the OMA standalone package under the MPL 2.0 (open source) licence.
              </div>    
            </div>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<title>Tax Prep Montreal</title>

<%= render 'quote' %>

<div class="container">

	<h2 class="text-center">Enjoy a stress-free tax season.</h2>
	<h2 class="lead text-center">Sit back and don't look back. We've got you covered.</h2>

	<br>
	<h2 class="text-center">How It Works</h2>
	<br>

	<%= render 'pages/features' %>

	<br>
	<!-- Embed Facebook page reviews  -->
<div id="widget_60e48782987798a30af99f1f994211406ee33ffe"></div>
<script type="text/javascript">
		(function(emconfig){
			emd = {
				config:emconfig
			};
			var head = document.getElementsByTagName('head')[0];
			var fileref = document.createElement('script');
			fileref.type = 'text/javascript';
			fileref.src = emconfig.config.site + '/js/partnerwidget.js';
			head.appendChild(fileref);
		})({
			config:{
				site:'https://www.reviewembed.com/'
				,code:'60e48782987798a30af99f1f994211406ee33ffe'
				,container:'widget_60e48782987798a30af99f1f994211406ee33ffe'
                ,js:[
                        "https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js",
                        "https://www.reviewembed.com/assets/lightslider.min.js?body=1"
                ]
                ,css:[
                        "https://www.reviewembed.com/assets/lightslider.min.css?body=1",
                        "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
                ]

			}
		});
</script>
<!-- / Embed Facebook page reviews  -->

	<br>

	<h2 class="lead text-center" name="important-dates">2015 Income Tax Season</h2>
	<h2 class="text-center">Important Dates</h2>

	<%= render 'pages/importantdates' %>
	<div class="row">
		<hr>
		<h2 class="text-center">Enjoy a stress-free tax season for as little as $129</h2>
		<br>
		<p class="text-center">
			<a class="typeform-share btn btn-primary btn-lg" href="https://eutait.typeform.com/to/OOIX17" data-mode="1" target="_blank" style=" width: 300px;">Get a quote >></a>
		</p>
	<br>
	</div>
</div>

app/views/pages/quote.html.erb
<title>Get a Quote | Tax Prep Montreal</title>

<%= render 'quote' %>

app/views/pages/services.html.erb
<head>
    <title>Services | Tax Prep Montreal</title>
</head>
<p class="text-center lead">Coming Soon</p>